[88107204] Remove unnecesary `force`
Fixes the following exception seen after run systems importer:

/Users/dabo/src/iris/lib/tasks/import_hospital_systems.thor:26:in
`import': undefined method `force' for nil:NilClass (NoMethodError)

We don't need to invoke `force` over the lazy collection becuase the
`each` iteration already calculates all array values.